SELECT * FROM [dbo].[olist_customers_dataset]

CREATE TABLE TB_ACT_OLIST_CUSTOMERS
(

CUSTOMER_ID NVARCHAR(150),
CUSTOMER_UNIQUE_ID NVARCHAR(150),
CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
CUSTOMER_CITY NVARCHAR(50),
CUSTOMER_STATE NVARCHAR(2)

)

INSERT INTO TB_ACT_OLIST_CUSTOMERS
SELECT * FROM olist_customers_dataset

SELECT * FROM TB_ACT_OLIST_CUSTOMERS