SELECT * FROM [dbo].[olist_geolocation_dataset]

CREATE TABLE TB_ACT_OLIST_GEOLOCATION
(

GEOLOCATION_ZIP_CODE_PREFIX	 NVARCHAR(15),
GEOLOCATION_LAT FLOAT,
GEOLOCATION_LNG FLOAT,
GEOLOCATION_CITY NVARCHAR(50),
GEOLOCATION_STATE NVARCHAR(2)

)

INSERT INTO TB_ACT_OLIST_GEOLOCATION
SELECT * FROM [dbo].[olist_geolocation_dataset]

SELECT * FROM TB_ACT_OLIST_GEOLOCATION