SELECT * FROM [dbo].[olist_orders_dataset]

CREATE TABLE TB_ACT_OLIST_ORDERS
(
    ORDER_ID NVARCHAR(150),
    CUSTOMER_ID NVARCHAR(150),
    ORDER_STATUS VARCHAR(30),
    ORDER_PURCHASE_TIMESTAMP DATE,
    ORDER_APPROVED_AT DATE,
    ORDER_DELIVERED_CARRIER_DATE DATE,
    ORDER_DELIVERED_CUSTOMER_DATE DATE,
    ORDER_ESTIMATED_DELIVERY_DATE DATE
);

INSERT INTO TB_ACT_OLIST_ORDERS
SELECT * FROM [dbo].[olist_orders_dataset]

SELECT * FROM TB_ACT_OLIST_ORDERS