SELECT * FROM [dbo].[olist_order_items_dataset]


CREATE TABLE TB_ACT_OLIST_ORDER_ITEMS
(

ORDER_ID NVARCHAR(150),
ORDER_ITEM_ID INT,
PRODUCT_ID NVARCHAR(150),
SELLER_ID NVARCHAR(150),
SHIPPING_LIMIT_DATE DATE,
PRICE FLOAT,
FREIGHT_VALUE FLOAT

)

INSERT INTO TB_ACT_OLIST_ORDER_ITEMS
SELECT * FROM [dbo].[olist_order_items_dataset]

SELECT * FROM TB_ACT_OLIST_ORDER_ITEMS
