SELECT * FROM [dbo].[TB_ACT_OLIST_CUSTOMERS]

-------

CREATE VIEW VW_PEDIDOS_POR_CLIENTE
AS

SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE, C.CUSTOMER_ZIP_CODE_PREFIX
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [TB_ACT_OLIST_CUSTOMERS] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID

-------

SELECT * FROM VW_PEDIDOS_POR_CLIENTE

