SELECT * FROM [dbo].[olist_sellers_dataset]

CREATE TABLE TB_ACT_OLIST_SELLERS

(

SELLER_ID NVARCHAR(150),
SELLER_ZIP_CODE_PREFIX NVARCHAR(15),
SELLER_CITY NVARCHAR(50),
SELLET_STATE NVARCHAR(2)

)

INSERT INTO TB_ACT_OLIST_SELLERS
SELECT * FROM [dbo].[olist_sellers_dataset]

SELECT * FROM TB_ACT_OLIST_SELLERS